# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bf3890dd3bb7159e0aced0a062eb343c40eb0c9e44f749aad778fc428a74d99f094120f065f71c81a4ec3bbdb320baf50ed4a3ac3712182e7c37f59aec50b3e

test:
  secret_key_base: ad70cd08694462044c49c33f7e0a74d30e3173bf29a1b936ae35a7b0a088a7da461134484f9220302989d0aa549315b9eaad85631f3923eba1e4939faebc1ae3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
